#!/usr/bin/env node
// Release helper: optional bump -> CHANGELOG from commits since last tag -> release commit -> annotated tag.
// Usage: node scripts/tag-release.mjs [patch|minor|major]
// Omit the argument to release the version already in package.json.
import { execSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';

const run = (cmd) => execSync(cmd, { encoding: 'utf8' }).trim();
const fail = (msg) => {
  console.error(`x ${msg}`);
  process.exit(1);
};

if (run('git status --porcelain')) fail('Working tree is dirty. Commit or stash changes first.');

const pkgPath = new URL('../package.json', import.meta.url);
const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));
const bump = process.argv[2];
if (bump) {
  const parts = pkg.version.split('.').map(Number);
  if (bump === 'major') [parts[0], parts[1], parts[2]] = [parts[0] + 1, 0, 0];
  else if (bump === 'minor') [parts[1], parts[2]] = [parts[1] + 1, 0];
  else if (bump === 'patch') parts[2] += 1;
  else fail(`Unknown bump "${bump}". Use: patch | minor | major`);
  pkg.version = parts.join('.');
  writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + '\n');
}
const tag = `v${pkg.version}`;

try {
  run(`git rev-parse -q --verify refs/tags/${tag}`);
  fail(`Tag ${tag} already exists.`);
} catch {
  // tag does not exist yet - good
}

let lastTag = null;
try {
  lastTag = run('git describe --tags --abbrev=0');
} catch {
  // no previous tag - first release
}
const commits = run(`git log ${lastTag ? `${lastTag}..HEAD` : 'HEAD'} --pretty=format:"- %s"`)
  .split('\n')
  .filter(Boolean);

const changelogPath = new URL('../CHANGELOG.md', import.meta.url);
const header =
  '# Changelog\n\nAll notable changes to AssistX are documented in this file.\nNew entries are generated by `scripts/tag-release.mjs` from commit messages since the last tag.\n';
const entry = `\n## [${pkg.version}]\n\n${commits.join('\n')}\n`;
const old = existsSync(changelogPath) ? readFileSync(changelogPath, 'utf8') : header;
const idx = old.indexOf('\n## ');
const next = idx === -1 ? old.trimEnd() + entry : old.slice(0, idx) + entry + old.slice(idx);
writeFileSync(changelogPath, next);

run('git add package.json CHANGELOG.md');
run(`git commit -m "chore: release ${tag}"`);
run(`git tag -a ${tag} -m "${tag}"`);

console.log(`Released ${tag}`);
console.log(`Push to trigger the release CI:\n\n  git push origin main && git push origin ${tag}\n`);
